
import { Service, Package, Order, WhyChooseUs, ServiceCategoryInfo } from './types';

export const services: Service[] = [
  {
    id: 'save-the-date-video',
    name: 'Save The Date Video',
    slug: 'save-the-date-video',
    category: 'invitation-videos',
    description: 'Create excitement with a beautiful Save The Date video. Perfect for sharing on social media.',
    price: 1500,
    originalPrice: 2000,
    priceType: 'starting',
    isFeatured: true,
    topRated: true,
    rating: 4.9,
    samples: [
      { type: 'video', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' },
      { type: 'image', url: 'https://i.ibb.co/pBVfNvdh/modern-wedding-invitation-card-design-with-bride-groom-13329-2351.jpg', imageHint: 'wedding couple' },
    ],
    inclusions: ['HD Quality Video (1080p)', 'Custom Text & Couple Names', '1 Song of Your Choice', 'Delivery in 2 days'],
    deliveryTime: '2-3 Business Days',
    tags: ['wedding'],
  },
  {
    id: 'wedding-invitation-video',
    name: 'Wedding Invitation Video',
    slug: 'wedding-invitation-video',
    category: 'invitation-videos',
    description: 'A cinematic wedding invitation video to impress your guests.',
    price: 2500,
    priceType: 'starting',
    isFeatured: false,
    topRated: true,
    rating: 4.8,
    samples: [
      { type: 'video', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' },
       { type: 'image', url: 'https://i.ibb.co/ccBJmTv8/Red-And-Gold-Illustrative-Indian-Movie-Poster-1.jpg', imageHint: 'wedding ceremony' },
    ],
    inclusions: ['2-3 Minute Full HD Video', 'Detailed Event Information', 'Photo & Video Integration', 'Voice Over option'],
    deliveryTime: '4-5 Business Days',
    tags: ['wedding', 'engagement'],
  },
  {
    id: 'digital-cards-wedding',
    name: 'Elegant Wedding E-Invite',
    slug: 'digital-cards-wedding',
    category: 'invitation-cards',
    description: 'Eco-friendly and modern digital cards (Image/PDF) for WhatsApp and email.',
    price: 800,
    originalPrice: 1000,
    priceType: 'fixed',
    isFeatured: true,
    topRated: true,
    rating: 4.9,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/pjvPdGKd/canva-purple-gold-aesthetic-watercolor-flower-wedding-invitation-y-H-34-W-a-U-E.jpg', imageHint: 'invitation card' },
      { type: 'image', url: 'https://i.ibb.co/Kzw1DzgS/aa3658076dafd6d8495d44b9806013a980d46aa91692708362.jpg', imageHint: 'floral invitation' },
    ],
    inclusions: ['High-Resolution JPEG/PNG', 'Print-ready PDF file', 'Clickable Google Maps Link', '2 Design Revisions'],
    deliveryTime: '1-2 Business Days',
    tags: ['wedding', 'engagement', 'anniversary'],
  },
  {
    id: 'digital-cards-birthday',
    name: 'Fun Birthday Invite',
    slug: 'digital-cards-birthday',
    category: 'invitation-cards',
    description: 'A fun and colorful invitation for birthday celebrations of all ages.',
    price: 700,
    priceType: 'fixed',
    isFeatured: false,
    topRated: false,
    rating: 4.7,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/ZwNH6kk/Birthday-invitation-card-scaled.webp', imageHint: 'birthday invitation' },
    ],
    inclusions: ['High-Resolution JPEG/PNG', '2 Design Revisions'],
    deliveryTime: '1 Business Day',
    tags: ['birthday'],
  },
    {
    id: 'cdr-file-card',
    name: 'Print-Ready (CDR) Cards',
    slug: 'cdr-file-card',
    category: 'invitation-cards',
    description: 'Get the source file of your card design in CorelDRAW (CDR) format for unlimited printing.',
    price: 1200,
    priceType: 'fixed',
    isFeatured: false,
    topRated: false,
    rating: 4.5,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/d0sWG3hf/b6e12aef38030c624290a53648f170ae.jpg', imageHint: 'elegant invitation' },
    ],
    inclusions: ['Fully-editable CDR file', 'All fonts used', 'Color palette information', 'Guidance for printing press'],
    deliveryTime: '2-3 Business Days',
    tags: ['wedding', 'engagement', 'anniversary', 'housewarming', 'babyshower'],
  },
   {
    id: 'cdr-file-wedding',
    name: 'Wedding Card CDR File',
    slug: 'cdr-file-wedding',
    category: 'invitation-cards',
    description: 'Source file for a premium wedding invitation card.',
    price: 1250,
    priceType: 'fixed',
    isFeatured: false,
    topRated: false,
    rating: 4.6,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/k2PyZNMQ/2b3cc905d7635ac992fb6b684bdf26d4.jpg', imageHint: 'luxury wedding' },
    ],
    inclusions: ['Editable CDR file', 'Fonts included', 'High-resolution assets'],
    deliveryTime: '1-2 Business Days',
    tags: ['wedding', 'cdr-file'],
  },
  {
    id: 'full-wedding-video-editing',
    name: 'Full Wedding Video Editing',
    slug: 'full-wedding-video-editing',
    category: 'video-editing',
    description: 'We edit your raw wedding footage into a beautiful, cinematic full-length movie.',
    price: 15000,
    priceType: 'starting',
    isFeatured: true,
    topRated: true,
    rating: 5.0,
    samples: [
       { type: 'video', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' },
       { type: 'image', url: 'https://i.ibb.co/V0M6FtPr/womens-banner.jpg', imageHint: 'wedding film' },
    ],
    inclusions: ['Editing up to 8 hours of footage', 'Color Grading & Correction', 'Sound Design & Mixing', 'Cinematic Highlight Reel (3-5 min)'],
    deliveryTime: '15-20 Business Days',
  },
  {
    id: 'highlight-reel-editing',
    name: 'Highlight Reel Editing',
    slug: 'highlight-reel-editing',
    category: 'video-editing',
    description: 'A short, dynamic highlight reel of your best wedding moments, perfect for sharing.',
    price: 8000,
    priceType: 'fixed',
    isFeatured: false,
    topRated: false,
    rating: 4.8,
    samples: [
       { type: 'video', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' },
       { type: 'image', url: 'https://i.ibb.co/gM6Tsmvm/mens-banner.jpg', imageHint: 'wedding highlight' },
    ],
    inclusions: ['3-5 minute highlight video', 'Editing up to 2 hours of footage', 'Cinematic Color Grading', 'Licensed Music'],
    deliveryTime: '7-10 Business Days',
  },
    {
    id: 'album-design',
    name: 'Classic Wedding Album',
    slug: 'album-design-classic',
    category: 'album-design',
    description: 'Professional and creative design for your wedding photo album.',
    price: 5000,
    priceType: 'starting',
    isFeatured: true,
    topRated: true,
    rating: 4.8,
    samples: [
       { type: 'image', url: 'https://i.ibb.co/xKSd1Tq6/1000132665.png', imageHint: 'wedding album' },
       { type: 'image', url: 'https://i.ibb.co/cSw3TXRX/canva-green-beige-cute-pastel-watercolor-carriage-aesthetic-baby-shower-invitation-Y6-Maar-KUp-Hk.jpg', imageHint: 'photo album' },
    ],
    inclusions: ['Design for 30-page album', 'Upto 150 photos', 'Creative Layouts', 'Print-ready soft copy'],
    deliveryTime: '7-10 Business Days',
  },
    {
    id: 'album-design-modern',
    name: 'Modern Magazine Style Album',
    slug: 'album-design-modern',
    category: 'album-design',
    description: 'A contemporary, magazine-style layout for your wedding photos.',
    price: 6500,
    priceType: 'starting',
    isFeatured: false,
    topRated: false,
    rating: 4.9,
    samples: [
       { type: 'image', url: 'https://i.ibb.co/cShTy3vv/e45b7b214df24fdbafb451cc5418d883.webp', imageHint: 'modern album' },
       { type: 'image', url: 'https://i.ibb.co/R405N9D5/il-570x-N-3016640146-goy6.jpg', imageHint: 'clean album' },
    ],
    inclusions: ['Design for 35-page album', 'Upto 200 photos', 'Minimalist & Elegant Layout', 'Print-ready soft copy'],
    deliveryTime: '8-12 Business Days',
  },
  {
    id: 'combo-basic',
    name: 'Card + Video Combo',
    slug: 'combo-basic',
    category: 'combo-packages',
    description: 'Perfect for getting started with a beautiful invitation set.',
    price: 2999,
    priceType: 'fixed',
    isFeatured: false,
    samples: [
       { type: 'image', url: 'https://i.ibb.co/x822fFKV/79a30036044340a7a315ec7f5b59c5bb6b24b72b1698059336.jpg', imageHint: 'wedding package' },
    ],
    inclusions: [ 'Standard Invitation Video', 'Matching Digital Card', '2 Revisions', 'Delivery in 4 days' ],
    deliveryTime: '4 Business Days',
  },
  {
    id: 'combo-premium-package',
    name: 'Premium Cinematic Combo',
    slug: 'combo-premium-package',
    category: 'combo-packages',
    description: 'Our most popular package for a stunning impression.',
    price: 4999,
    priceType: 'fixed',
    isFeatured: false,
    samples: [
       { type: 'image', url: 'https://i.ibb.co/Q3QyT8nj/a3bce99796b09f0738ff35170778cdc8392804c51688993196.jpg', imageHint: 'premium wedding' },
    ],
    inclusions: [ 'Premium Cinematic Video', 'Matching Premium Digital Card', 'Save The Date GIF', '4 Revisions', 'Priority Delivery (3 days)'],
    deliveryTime: '3 Business Days',
  },
    {
    id: 'combo-full',
    name: 'Full Wedding Invite Combo',
    slug: 'combo-full',
    category: 'combo-packages',
    description: 'A complete solution for all your wedding invitation needs.',
    price: 7999,
    priceType: 'fixed',
    isFeatured: false,
    samples: [
       { type: 'image', url: 'https://i.ibb.co/JjyH9D19/29dfd12fed210708903674bcf3babf7e.jpg', imageHint: 'luxury wedding package' },
    ],
    inclusions: ['Everything in Premium Combo', 'Reception Invitation Video', 'Thank You Card Digital', 'Unlimited Revisions', 'Dedicated Designer'],
    deliveryTime: '5-7 Business Days',
  },
  {
    id: 'combo-premium',
    name: 'Premium Invite Combo',
    slug: 'combo-premium',
    category: 'combo-packages',
    description: 'The ultimate package for a grand wedding announcement.',
    price: 4999,
    priceType: 'fixed',
    isFeatured: false,
    topRated: true,
    rating: 5.0,
    samples: [
       { type: 'image', url: 'https://i.ibb.co/chcW98zq/simple-invitation-free-google-docs-template-t-376x520.webp', imageHint: 'luxury wedding' },
    ],
    inclusions: ['Premium Cinematic Video', 'Matching Digital Card (PDF/JPG)', 'Animated Save the Date GIF', 'Priority Support'],
    deliveryTime: '5-7 Business Days',
  },
  {
    id: 'digital-cards-babyshower',
    name: 'Cute Baby Shower Invite',
    slug: 'digital-cards-babyshower',
    category: 'invitation-cards',
    description: 'An adorable invitation to celebrate the upcoming arrival.',
    price: 750,
    priceType: 'fixed',
    isFeatured: false,
    topRated: false,
    rating: 4.6,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/6cNfkwJh/canva-brown-illustrative-baby-shower-flyer-ZQ9t-OEPEVs.jpg', imageHint: 'baby shower' },
    ],
    inclusions: ['High-Resolution JPEG/PNG', '2 Design Revisions'],
    deliveryTime: '1 Business Day',
    tags: ['babyshower'],
  },
  {
    id: 'digital-cards-engagement',
    name: 'Engagement Party E-Invite',
    slug: 'digital-cards-engagement',
    category: 'invitation-cards',
    description: 'A stylish e-invite to announce your engagement.',
    price: 750,
    priceType: 'fixed',
    isFeatured: false,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/7ddd4sMg/engagement-party-invitation-card-template-hd-design-cfdcbfe093f48ecb080bab140b8b157a-screen.jpg', imageHint: 'engagement party' },
    ],
    inclusions: ['High-Resolution JPEG/PNG', '2 Design Revisions'],
    deliveryTime: '1 Business Day',
    tags: ['engagement'],
  },
    {
    id: 'digital-cards-housewarming',
    name: 'Housewarming Party Invite',
    slug: 'digital-cards-housewarming',
    category: 'invitation-cards',
    description: 'Invite friends and family to your new home with a warm invitation.',
    price: 650,
    priceType: 'fixed',
    isFeatured: false,
    samples: [
      { type: 'image', url: 'https://i.ibb.co/gMLZLvnb/Screenshot-2025-12-14-19-19-25-58-40deb401b9ffe8e1df2f1cc5ba480b12.jpg', imageHint: 'new home' },
    ],
    inclusions: ['High-Resolution JPEG/PNG', '2 Design Revisions'],
    deliveryTime: '1 Business Day',
    tags: ['housewarming'],
  },
];

export const packages: Package[] = [
  {
    id: 'combo-basic',
    name: 'Card + Video Combo',
    price: '₹2,999',
    description: 'Perfect for getting started with a beautiful invitation set.',
    features: [
      'Standard Invitation Video',
      'Matching Digital Card',
      '2 Revisions',
      'Delivery in 4 days',
    ],
    isBestValue: false,
  },
  {
    id: 'combo-premium-package',
    name: 'Premium Cinematic Combo',
    price: '₹4,999',
    description: 'Our most popular package for a stunning impression.',
    features: [
      'Premium Cinematic Video',
      'Matching Premium Digital Card',
      'Save The Date GIF',
      '4 Revisions',
      'Priority Delivery (3 days)',
    ],
    isBestValue: true,
  },
  {
    id: 'combo-full',
    name: 'Full Wedding Invite Combo',
    price: '₹7,999',
    description: 'A complete solution for all your wedding invitation needs.',
    features: [
      'Everything in Premium Combo',
      'Reception Invitation Video',
      'Thank You Card Digital',
      'Unlimited Revisions',
      'Dedicated Designer',
    ],
    isBestValue: false,
  },
];

export const whyChooseUs: WhyChooseUs[] = [
  {
    icon: 'Sparkles',
    title: 'Professional Work',
    description: 'Our experienced designers create stunning visuals that tell your story beautifully.'
  },
  {
    icon: 'Film',
    title: 'On-Time Delivery',
    description: 'We understand the importance of deadlines and guarantee timely delivery of all projects.'
  },
  {
    icon: 'Heart',
    title: 'Affordable Pricing',
    description: 'Get premium quality services at prices that won’t stretch your wedding budget.'
  },
  {
    icon: 'Users',
    title: 'Real Human Support',
    description: 'Our team is always available on WhatsApp and phone to assist you at every step.'
  },
];

export const serviceCategories: ServiceCategoryInfo[] = [
    {
      id: 'invitation-videos',
      name: 'Invitation Videos',
      description: 'Announce your special day with a stunning video that captures your love story.',
      href: '/invitation-videos',
    },
    {
      id: 'invitation-cards',
      name: 'Invitation Cards',
      description: 'Elegant and modern digital & printable cards for every wedding style.',
      href: '/invitation-cards',
    },
    {
        id: 'video-editing',
        name: 'Wedding Video Editing',
        description: 'We edit your raw footage into a beautiful, cinematic wedding film.',
        href: '/video-editing',
    },
    {
      id: 'album-design',
      name: 'Album Designs',
      description: 'Treasure your memories with a beautifully designed, professional wedding album.',
      href: '/album-design',
    },
    {
      id: 'cdr-files',
      name: 'CDR Files',
      description: 'Get print-ready CorelDRAW source files for your invitation cards.',
      href: '/invitation-cards?filter=cdr',
    },
    {
      id: 'combo-packages',
      name: 'Combo Packages',
      description: 'Get the best value with our curated packages combining our most popular services.',
      href: '/packages',
    },
     {
      id: 'website-development',
      name: 'Full Professional Website',
      description: 'We can create a professional website for your personal or business needs.',
      href: '/contact',
    },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    userId: 'user123',
    fullName: 'Rohan Sharma',
    phoneNumber: '+919876543210',
    email: 'rohan.sharma@example.com',
    weddingDate: '2024-12-15',
    selectedServiceId: 'combo-premium-package',
    messageNotes: 'Looking for a royal theme.',
    status: 'In Progress',
    paymentStatus: 'Paid',
    orderDate: '2024-10-20',
  },
  {
    id: 'ORD002',
    userId: 'user124',
    fullName: 'Priya Patel',
    phoneNumber: '+919123456789',
    email: 'priya.patel@example.com',
    weddingDate: '2025-01-22',
    selectedServiceId: 'save-the-date-video',
    messageNotes: 'Need it urgently.',
    status: 'Pending',
    paymentStatus: 'Advance',
    orderDate: '2024-10-22',
  },
    {
    id: 'ORD003',
    userId: 'user125',
    fullName: 'Ankit Desai',
    phoneNumber: '+919988776655',
    email: 'ankit.desai@example.com',
    weddingDate: '2024-11-30',
    selectedServiceId: 'album-design',
    messageNotes: 'We have about 200 photos for a 40-page album.',
    status: 'Delivered',
    paymentStatus: 'Paid',
    orderDate: '2024-09-15',
  },
    {
    id: 'ORD004',
    userId: 'user126',
    fullName: 'Sneha Verma',
    phoneNumber: '+919223344556',
    email: 'sneha.verma@example.com',
    weddingDate: '2025-02-10',
    selectedServiceId: 'digital-cards-wedding',
    messageNotes: '',
    status: 'Paid',
    paymentStatus: 'Paid',
    orderDate: '2024-10-23',
  },
];

    
